export enum ECuisineType {
  american = 'american',
  asian = 'asian',
  british = 'british',
  caribbean = 'caribbean',
  'central europe' = 'central europe',
  chinese = 'chinese',
  'eastern europe' = 'eastern europe',
  french = 'french',
  greek = 'greek',
  indian = 'indian',
  italian = 'italian',
  japanese = 'japanese',
  korean = 'korean',
  kosher = 'kosher',
  mediterranean = 'mediterranean',
  mexican = 'mexican',
  'middle eastern' = 'middle eastern',
  nordic = 'nordic',
  'south american' = 'south american',
  'south east asian' = 'south east asian',
  world = 'world',
}
