export enum EDishType {
  'alcohol cocktail' = 'alcohol cocktail',
  'biscuits and cookies' = 'biscuits and cookies',
  bread = 'bread',
  cereals = 'cereals',
  'condiments and sauces' = 'condiments and sauces',
  desserts = 'desserts',
  drinks = 'drinks',
  egg = 'egg',
  'ice cream and custard' = 'ice cream and custard',
  'main course' = 'main course',
  pancake = 'pancake',
  pasta = 'pasta',
  pastry = 'pastry',
  'pies and tarts' = 'pies and tarts',
  pizza = 'pizza',
  preps = 'preps',
  preserve = 'preserve',
  salad = 'salad',
  sandwiches = 'sandwiches',
  seafood = 'seafood',
  'side dish' = 'side dish',
  soup = 'soup',
  'special occasions' = 'special occasions',
  starter = 'starter',
  sweets = 'sweets',
}
